export const APIAddress = 'https://dm.rolevik.site:8443'
// export const APIAddress = 'http://127.0.0.1:8000'
export const getCharsheetEndPoint = '/generate_charsheet_review'
export const cleanLogEndPoint = '/clean_log'
export const cleanParticipantsTextEndPoint = "/events/clean_participants_text"
export const createLotteryEndPoint = "/events/create_lottery"
export const rewardsWorkEndPoint = "/arbiters/rewards_work"
export const getChecksEndPoint = "/economics/get_checks"
export const claimedItemsGetEndPoint = "/claimed_items/get_items"
export const claimedItemsCreateEndPoint = "/claimed_items/create"
export const claimedItemsDeleteEndPoint = "/claimed_items/delete"
export const claimedItemsUpdateEndPoint = "/claimed_items/update"
export const claimedItemsApproveEndPoint = "/claimed_items/approve"